import streamlit as st

# Sample data: Replace this with your actual data
power_plant_data = {
    "01ANGAT_M": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01ANGAT_M%20count.PNG", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01ANGAT_M%20snake.PNG", "Snakeplot for each Cluster of this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01ANGAT_M%20time%20dist.PNG", "Time Distribution of Clusters for this Generator")],
    "01BAUANG_GS1": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01BAUANG_GS1%20count.PNG", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01BAUANG_GS1%20snake.PNG", "Snakeplot for each Cluster of this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01BAUANG_GS1%20time%20dist.PNG", "Time Distribution of Clusters for this Generator")],
    "01CASECN_GO1": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01CASECN_G01%20count.PNG", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01CASECN_G01%20snake.PNG", "Snakeplot for each Cluster of this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01CASECN_G01%20time%20dist.PNG", "Time Distribution of Clusters for this Generator")],
    "01GNPD_U01": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01GNPD_U01%20count.PNG", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01GNPD_U01%20snake.PNG", "Snakeplot for each Cluster of this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01GNPD_U01%20time%20dist.PNG", "Time Distribution of Clusters for this Generator")], 
    "01LIMAY_U08": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01LIMAY_U08%20count.PNG", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01LIMAY_U08%20snake.PNG", "Snakeplot for each Cluster of this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01LIMAY_U08%20time%20dist.PNG", "Time Distribution of Clusters for this Generator")],
    "01MAGAT_U01": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01MAGAT_U01%20count.PNG", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01MAGAT_U01%20snake.PNG", "Snakeplot for each Cluster of this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01MAGAT_U01%20time%20dist.PNG", "Time Distribution of Clusters for this Generator")],
    "01SROQUE_U01": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01SROQUE_U01%20count.PNG", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01SROQUE_U01%20snake.PNG", "Snakeplot for each Cluster of this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01SROQUE_U01%20time%20dist.PNG", "Time Distribution of Clusters for this Generator")],
    "01SUAL_G01": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01SUAL_G01%20count.PNG", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01SUAL_G01%20snake.PNG", "Snakeplot for each Cluster of this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01SUAL_G01%20time%20dist.PNG", "Time Distribution of Clusters for this Generator")], 
    "01S_ENRO_G01": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01S_ENRO_G01%20count.PNG", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01S_ENRO_G01%20snake.PNG", "Snakeplot for each Cluster of this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/01S_ENRO_G01%20time%20dist.PNG", "Time Distribution of Clusters for this Generator")],
    "02TMOBIL_G01": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/02TMOBIL_G01%20count.PNG", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/02TMOBIL_G01%20snake.PNG", "Snakeplot for each Cluster of this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/02TMOBIL_G01%20time%20dist.PNG", "Time Distribution of Clusters for this Generator")], 
    "03AVION_U01": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03AVION_U01%20count.PNG", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03AVION_U01%20snake.PNG", "Snakeplot for each Cluster of this Generator"), ("", "Time Distribution of Clusters for this Generator")],
    "03ILIJAN_G01": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03ILIJAN_G01%20count.PNG", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03ILIJAN_G01%20snake.PNG", "Snakeplot for each Cluster of this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03ILIJAN_G01%20time%20dist.PNG", "Time Distribution of Clusters for this Generator")], 
    "03KAL_G01": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03KAL_G01%20count.PNG", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03KAL_G01%20snake.PNG", "Snakeplot for each Cluster of this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03KAL_G01%20time%20dist.PNG", "Time Distribution of Clusters for this Generator")],
    "03PAGBIL_G03": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03PAGBIL_G03%20count.PNG", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03PAGBIL_G03%20snake.PNG", "Snakeplot for each Cluster of this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03PAGBIL_G03%20time%20dist.PNG", "Time Distribution of Clusters for this Generator")],
    "03QPPL_G01": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03QPPL_G01%20count.PNG", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03QPPL_G01%20snake.PNG", "Snakeplot for each Cluster of this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03QPPL_G01%20time%20dist.PNG", "Time Distribution of Clusters for this Generator")],
    "03SBPL_G01": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03SBPL_G01%20count.PNG", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03SBPL_G01%20snake.PNG", "Snakeplot for each Cluster of this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03SBPL_G01%20time%20dist.PNG", "Time Distribution of Clusters for this Generator")],
    "03SNGAB_G01": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03SNGAB_G01%20count.png", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03SNGAB_G01%20snake.png", "Snakeplot for each Cluster of this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03SNGAB_G01%20time%20dist.png", "Time Distribution of Clusters for this Generator")],
    "03STA-RI_G03": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03STA-RI_G03%20count.png", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03STA-RI_G03%20snake.png", "Snakeplot for each Cluster of this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03STA-RI_G03%20time%20dist.png", "Time Distribution of Clusters for this Generator")],
    "03STA-RI_G05": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03STA-RI_G05%20count.png", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03STA-RI_G05%20snake.png", "Snakeplot for each Cluster of this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03STA-RI_G05%20time%20dist.png", "Time Distribution of Clusters for this Generator")],
    "03TIWI_A": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03TIWI_A%20count.PNG", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03TIWI_A%20snake.PNG", "Snakeplot for each Cluster of this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/03TIWI_A%20time%20dist.PNG", "Time Distribution of Clusters for this Generator")], 
    "04LEYTE_A": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/04LEYTE_A%20count.PNG", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/04LEYTE_A%20snake.PNG", "Snakeplot for each Cluster of this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/04LEYTE_A%20time%20dist.PNG", "Time Distribution of Clusters for this Generator")],
    "04LGPP_G01": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/04LGPP_G01%20count.PNG", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/04LGPP_G01%20snake.PNG", "Snakeplot for each Cluster of this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/04LGPP_G01%20time%20dist.PNG", "Time Distribution of Clusters for this Generator")], 
    "06NTNEGB_G01": [("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/06NTNEGB_G01%20count.PNG", "Number of Clusters for this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/06NTNEGB_G01%20snake.PNG", "Snakeplot for each Cluster of this Generator"), ("https://raw.githubusercontent.com/Jumberrr/Maroon_Archers/main/Capstone/images/06NTNEGB_G01%20time%20dist.PNG", "Time Distribution of Clusters for this Generator")]
}

# Streamlit app

st.title("Watts Up Pinas?!")

# Dropdown for selecting resource_id
selected_resource_id = st.selectbox("Select a generator (resource_id)", list(power_plant_data.keys()))

# Display the selected resource_id
st.write(f"Selected generator (resource_id): {selected_resource_id}")

# Display the corresponding images with custom titles
images_with_titles = power_plant_data.get(selected_resource_id, [])
for image_url, title in images_with_titles:
    st.image(image_url, caption=title, use_column_width=True)